# Form implementation generated from reading ui file './res/ui/lapse_review_ratio_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LapseReviewRatioForm(object):
    def setupUi(self, LapseReviewRatioForm):
        LapseReviewRatioForm.setObjectName("LapseReviewRatioForm")
        LapseReviewRatioForm.resize(319, 109)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LapseReviewRatioForm.sizePolicy().hasHeightForWidth())
        LapseReviewRatioForm.setSizePolicy(sizePolicy)
        LapseReviewRatioForm.setMinimumSize(QtCore.QSize(128, 32))
        self.lapseReviewRatioFormLayout = QtWidgets.QVBoxLayout(LapseReviewRatioForm)
        self.lapseReviewRatioFormLayout.setContentsMargins(0, 0, 0, 0)
        self.lapseReviewRatioFormLayout.setObjectName("lapseReviewRatioFormLayout")
        self.lapseReviewRatioForm = QtWidgets.QGroupBox(parent=LapseReviewRatioForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lapseReviewRatioForm.sizePolicy().hasHeightForWidth())
        self.lapseReviewRatioForm.setSizePolicy(sizePolicy)
        self.lapseReviewRatioForm.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lapseReviewRatioForm.setCheckable(True)
        self.lapseReviewRatioForm.setObjectName("lapseReviewRatioForm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.lapseReviewRatioForm)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lapseReviewRatioFormLayout.addWidget(self.lapseReviewRatioForm)

        self.retranslateUi(LapseReviewRatioForm)
        QtCore.QMetaObject.connectSlotsByName(LapseReviewRatioForm)

    def retranslateUi(self, LapseReviewRatioForm):
        _translate = QtCore.QCoreApplication.translate
        self.lapseReviewRatioForm.setToolTip(_translate("LapseReviewRatioForm", "Reverse card lapses based on the number of correct review answers they have."))
        self.lapseReviewRatioForm.setTitle(_translate("LapseReviewRatioForm", "Lapse Review Ratio"))
