# Form implementation generated from reading ui file 'lapse_review_ratio_form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LapseReviewRatioWidget(object):
    def setupUi(self, LapseReviewRatioWidget):
        LapseReviewRatioWidget.setObjectName("LapseReviewRatioWidget")
        LapseReviewRatioWidget.resize(319, 109)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LapseReviewRatioWidget.sizePolicy().hasHeightForWidth())
        LapseReviewRatioWidget.setSizePolicy(sizePolicy)
        LapseReviewRatioWidget.setMinimumSize(QtCore.QSize(128, 32))
        self.lapseReviewRatioFormLayout = QtWidgets.QVBoxLayout(LapseReviewRatioWidget)
        self.lapseReviewRatioFormLayout.setContentsMargins(0, 0, 0, 0)
        self.lapseReviewRatioFormLayout.setObjectName("lapseReviewRatioFormLayout")
        self.lapseReviewRatioGroup = QtWidgets.QGroupBox(parent=LapseReviewRatioWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lapseReviewRatioGroup.sizePolicy().hasHeightForWidth())
        self.lapseReviewRatioGroup.setSizePolicy(sizePolicy)
        self.lapseReviewRatioGroup.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lapseReviewRatioGroup.setCheckable(True)
        self.lapseReviewRatioGroup.setObjectName("lapseReviewRatioGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.lapseReviewRatioGroup)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lapseReviewRatioLineEdit = QtWidgets.QLineEdit(parent=self.lapseReviewRatioGroup)
        self.lapseReviewRatioLineEdit.setObjectName("lapseReviewRatioLineEdit")
        self.verticalLayout_2.addWidget(self.lapseReviewRatioLineEdit)
        self.lapseReviewRatioLineEditLabel = QtWidgets.QLabel(parent=self.lapseReviewRatioGroup)
        self.lapseReviewRatioLineEditLabel.setObjectName("lapseReviewRatioLineEditLabel")
        self.verticalLayout_2.addWidget(self.lapseReviewRatioLineEditLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lapseReviewRatioFormLayout.addWidget(self.lapseReviewRatioGroup)

        self.retranslateUi(LapseReviewRatioWidget)
        QtCore.QMetaObject.connectSlotsByName(LapseReviewRatioWidget)

    def retranslateUi(self, LapseReviewRatioWidget):
        _translate = QtCore.QCoreApplication.translate
        self.lapseReviewRatioGroup.setToolTip(_translate("LapseReviewRatioWidget", "<html><head/><body><p>Configure lapse review ratio threshold</p></body></html>"))
        self.lapseReviewRatioGroup.setTitle(_translate("LapseReviewRatioWidget", "Lapse Review Ratio"))
        self.lapseReviewRatioLineEditLabel.setText(_translate("LapseReviewRatioWidget", "Lapse review ratio threshold"))
